### ISSUE TITLE
haxelib mysql database being down

### ISSUE THREAD

**Issue by HomuHomu833** [HaxeFoundation/haxelib#679]
the both site and `haxelib install` doing this
```bash
Uncaught exception - mysql.c(509) : Failed to connect to mysql server : Failed to connect on host 'haxelib-mysql-57-primary'

Called from a C function
Called from website/Server.hx line 52
Called from haxelib/server/SiteDb.hx line 127
Called from /usr/local/share/haxe/std/neko/_std/sys/db/Mysql.hx line 202
```

**Comment by HomuHomu833** [comment]
seems to be up now, closing

**Comment by tobil4sk** [comment]
This has been solved on the live server, but I'm reopening this issue because it hasn't been solved in the infra files so the issue will return if we push any updates.

cc @kLabz

**Comment by bglogic** [comment]
The live server is down. The issue reported by @HomuHomu833 still persists, affecting both site and `haxelib install`.

**Comment by andyli** [comment]
The k8s cluster was auto updated and that's probably why the image change was reverted to the helm chart version.

I've manually changed the image to `docker.io/bitnamilegacy/mysql:5.7.43-debian-11-r73` again. Still need a fix to the terraform files.
